# Generated by Django 5.0.6 on 2024-06-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrestedperson',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='arrested_people/'),
        ),
        migrations.AddField(
            model_name='fallensoldier',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='fallen_soldiers/'),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='missing_people/'),
        ),
    ]
