# Generated by Django 5.0.6 on 2024-06-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_arrestedperson_photo_fallensoldier_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrestedperson',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/arrested_people/'),
        ),
        migrations.AlterField(
            model_name='fallensoldier',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/fallen_soldiers/'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/missing_people/'),
        ),
    ]
