# Generated by Django 5.0.6 on 2024-06-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_arrestedperson_photo_alter_fallensoldier_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fallensoldier',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='fallen_soldiers/'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='missing_people/'),
        ),
    ]
